#Makefile ejercicio1

Ejercicio1 : Ejercicio1.o
	gcc -Wall -Wshadow -Wextra -o Ejercicio1 Ejercicio1.o

Ejercicio1.o : Ejercicio1.c
	gcc -Wall -Wshadow -Wextra -c  Ejercicio1.c

clean:
	@rm -f *.o Ejercicio1